zoo_one = Zoo.create(name: 'Alabama Gulf Coast Zoo', state: 'Alabama', facility: 'Regular', address: '1204 Gulf Shores Pkwy, Gulf Shores, AL 36542')
zoo_two = Zoo.create(name: 'Audubon Bird Sanctuary', state: 'Alabama', facility: 'Bird Sanctuary', address: '1201 Pawlings Rd, Audubon, PA 19403')
zoo_three = Zoo.create(name: 'Alameda Park Zoo', state: 'New Mexico', facility: 'Park', address: '1321 N White Sands Blvd, Alamogordo, NM 88310')
zoo_four = Zoo.create(name: 'Victory Ranch', state: 'New Mexico', facility: 'Horse Zoo', address: 'NM-434, Mora, NM 87732')
zoo_five = Zoo.create(name: 'The Whale Museum', state: 'Washington', facility: 'Whales', address: '62 1st St, Friday Harbor, WA 98250')
